sudo: required
services:
  - docker

# before_install:
#   - export CHROME_BIN=chromium-browser
#   - export DISPLAY=:99.0
#   - sh -e /etc/init.d/xvfb start
#   - docker build -t parthgupta13/student-frontend-test -f ./student-frontend/Dockerfile.dev ./student-frontend
  
script:
  # - docker run parthgupta13/student-frontend-test npm run test_headless
  - docker build -t parthgupta13/student-frontend ./student-frontend
  - docker build -t parthgupta13/student-backend ./student-backend
  - docker build -t parthgupta13/student-nginx ./nginx

after_success:
  
  # Login in to docker 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Pushing images to dockerhub
  - docker push parthgupta13/student-frontend
  - docker push parthgupta13/student-backend
  - docker push parthgupta13/student-nginx
  
deploy:
  edge: true
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "student-management"
  env: "StudentManagement-env"
  bucket_name: "elasticbeanstalk-ap-south-1-655159759760"
  bucket_path: "docker-student"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY  
