version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password
  student-frontend:
    build:
      dockerfile: Dockerfile
      context: ./student-frontend
  student-backend:
    build:
      dockerfile: Dockerfile
      context: ./student-backend
    depends_on:
      - postgres
    environment:
      - PGHOST=postgres
  student-nginx:
    depends_on:
      - student-backend
      - student-frontend
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '4000:80'